#########################################################################################
# General
#########################################################################################
spring.application.name=sdtooling-be

#########################################################################################
# Json object mapper config
#########################################################################################
# TODO: con spring boot 2 funzionava: con il 3 non sembra funzionare (usato @JsonFormat(with = Feature.ACCEPT_CASE_INSENSITIVE_PROPERTIES))
spring.jackson.mapper.accept-case-insensitive-enums=true

#########################################################################################
# Schema Sync repository absolute path
#########################################################################################
# absolute path to the schema repository synced by the schema-synch-adapter
schema-sync-service.repository-path=

#########################################################################################
# Feign clients
#########################################################################################
# logging level (NONE, BASIC, HEADERS, FULL)
feign.client.config.default.logger-level=FULL
# timeouts in milliseconds
feign.client.config.default.connect-timeout=5000
feign.client.config.default.read-timeout=15000

#########################################################################################
# Catalogue Adapter client
#########################################################################################
# url to the tier2 tls gateway of the catalog adapter application
#catalogue-adapter.tier2-gateway.url=https://t2.gaiax-edc-dev-catalogue.dev.simpl-europe.eu
catalogue-adapter.tier2-gateway.url=https://tls.authority.authority01.sandbox-cat-dat.simpl-europe.eu
# path prefix to be used to call catalogue apis through the gateway
#catalogue-adapter.tier2-gateway.path-prefix=/catalogue-adapter-service
catalogue-adapter.tier2-gateway.path-prefix=/adapter
catalogue-adapter.mock.revoke-resource-description=true


#########################################################################################
# federated-catalogue client
#########################################################################################
# url to the tier2 tls gateway of the federated catalog application
#federated-catalogue.tier2-gateway.url=https://t2.gaiax-edc-dev-catalogue.dev.simpl-europe.eu
federated-catalogue.tier2-gateway.url=https://tls.authority.authority01.sandbox-cat-dat.simpl-europe.eu
# tier2 tls gateway path configured as route rule to the federated catalog application
#federated-catalogue.tier2-gateway.path-prefix=/fc-service
federated-catalogue.tier2-gateway.path-prefix=/fc


#########################################################################################
# Web MVC config
#########################################################################################
server.port=8080
spring.mvc.pathmatch.matching-strategy=ANT_PATH_MATCHER

# http sessions disabled
server.servlet.session.timeout=0
server.servlet.session.persistent=false

# optional list (comma separated) of allowed origins or * to allow all origins
# if empty no cross calls are allowed
web.mvc.cors.allowed-origins=

# if true the Simpl-Cloud-Gateway JWT token must be present as Bearer in any API request
web.mvc.bearer-token.required=true

# optional list (comma separated) of allowed paths (ant matcher expressions) to skip JWT token check (ex: actuator health paths)
web.mvc.bearer-token.allowed-paths=/actuator/health/*,/status

# max size limit for single uploaded file (413 - Request Entity Too Large)
spring.servlet.multipart.max-file-size=2MB
# max size limit for whole request (413 - Request Entity Too Large)
spring.servlet.multipart.max-request-size=8MB


#########################################################################################
# Required components config
#########################################################################################
# url to the asset-orchestrator participant service
asset-orchestrator.service.url=http://localhost:9084
# url to the IAA AuthenticationProvider internal service
authentication-provider.service.url=http://localhost:9081
# url to the connector adapter internal service
connector-adapter.service.url=http://localhost:8085
# url to the schema sync adapter internal service
schema-sync-adapter.service.url=http://localhost:8086


#########################################################################################
# Management
#########################################################################################

# forcing healt probes (livenes and readiness) to be enabled if application is not running as root user
management.endpoint.health.probes.enabled=true


#########################################################################################
# Open Telemetry
#########################################################################################
# disables the OpenTelemetry SDK (true on local dev)
otel.sdk.disabled=true

# resource attributes used to identify the service and environment
otel.resource.attributes.deployment.environment=local-dev
otel.resource.attributes.service.name=sdtooling-api-be

# context propagation type
otel.propagators=tracecontext

# exporter type (otlp, jaeger, zipkin, etc.)
otel.traces.exporter=otlp
# protocol used by the OTLP exporter (http/protobuf or grpc)
otel.exporter.otlp.protocol=http/protobuf
# collector endpoint for the OTLP exporter
otel.exporter.otlp.endpoint=http://localhost:4318

# disable logs exporter (to avoid performance issue on production)
otel.logs.exporter=none

# disable automatic JDBC instrumentation
otel.instrumentation.jdbc.enabled=false
