# log4j2.xml belongs to the common loggin library
# log4j2-app.xml overrides some configuration for the application (e.g. levels)
log4j2.configurationFile=classpath:log4j2.xml,classpath:log4j2-app.xml