#########################################################################################
# Swagger ui & api docs
#########################################################################################
springdoc.api-docs.path=/api-docs
springdoc.api-docs.version=OPENAPI_3_0
springdoc.swagger-ui.path=/swagger-ui

# OpenAPI groups configuration: each group maps to controllers and is displayed separately in Swagger UI
openapi-config.groups[0].name=v1
openapi-config.groups[0].display-name=API v1
openapi-config.groups[0].packages-to-scan=eu.europa.ec.simpl.sdtoolingbe.controller.v1
openapi-config.groups[1].name=v2
openapi-config.groups[1].display-name=API v2
openapi-config.groups[1].packages-to-scan=eu.europa.ec.simpl.sdtoolingbe.controller.v2
openapi-config.groups[2].name=v3
openapi-config.groups[2].display-name=API v3
openapi-config.groups[2].packages-to-scan=eu.europa.ec.simpl.sdtoolingbe.controller.v3

# comma separated list of servers url to be used by swagger
openapi-config.servers=https://creation-wizard-api.dev.simpl-europe.eu

# Security enabled (default=false)
openapi-config.security.enabled=true

# Set the title for Swagger UI
openapi-config.title=SD Tooling API
openapi-config.description=The APIs described in the following document enable the management\n\
    of the lifecycle for creating a Resource Description on the provider side, including\n\
    its publication on the federated catalogue. The available APIs allow to define\n\
    access and usage policies, specify the Resource Address on the provider side,\n\
    and manage the validation and publication process on the federated catalogue.\n\
    \n\
    ## Business Context\n\
    \n\
    The API facilitates the creation and management of Resource Descriptions in a federated data space. It enables providers to publish metadata about their data assets on a federated catalogue, define access and usage policies, and manage the validation and publication workflow. This supports discoverability and interoperability across the data ecosystem.\n\
    \n\
    \n\
    ### Key Actors\n\
    \n\
    - **Provider**: Creates and publishes Resource Descriptions, defines policies, and manages validation.\n\
    \n\
    - **Governance Authority**: Hosts the Federated Catalogue\n\
    \n\
    ### Typical Flow\n\
    \n\
    1. Create a Resource Description.\n\
    \n\
    2. Define access and usage policies.\n\
    \n\
    3. Specify the Resource Address.\n\
    \n\
    4. Submit the Resource Description for validation\n\
    \n\
    5. Publish the Resource Description on the federated catalogue
