{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-creation-wizard-api
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    acme.cert-manager.io/http01-edit-in-place: "true"
    kubernetes.io/ingress.class: {{ .Values.ingress.ingressClass }}
spec:
  tls:
    - hosts:
        - creation-wizard-api.{{ .Values.domain }}
      secretName: creation-wizard-api-tls
  rules:
    - host: creation-wizard-api.{{ .Values.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-creation-wizard-api
                port:
                  number: {{ .Values.servicePort }}
{{- end }}
