apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-creation-wizard-api
spec:
  selector:
    app: sd-api
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
